### ISSUE TITLE
Consider dropping support for IE < 8, even optionally?

### ISSUE THREAD

**Issue by adamwathan** [mathiasbynens/cssesc#18]
Right now `:` is escaped as `\3A ` instead of `\:` to support really old versions of IE, like 6 and 7.

This is a bit of a pain because of a bug in `css-loader` that strips the leading `\` from these sort of escape sequences:

https://github.com/webpack-contrib/css-loader/issues/578

It's been open for about 1.5 years and is apparently a difficult fix, but it only affects me personally (and other [tailwindcss](https://github.com/tailwindcss/tailwindcss) users) in the case of the `:` character.

Since market share for IE < 8 is basically zero, it would be amazing if there was a way to just use `\:` instead of `\3A `.

Thanks so much for this great library 👍

**Comment by mathiasbynens** [comment]
I’d be fine with releasing a new major cssesc version without escapes for legacy browsers. Care to submit a PR?

**Comment by adamwathan** [comment]
Awesome thanks, PR'd in #19, let me know if I missed anything 👍
