### ISSUE TITLE
Escaping for js libraries (jquery/sizzle)

### ISSUE THREAD

**Issue by PandaWood** [mathiasbynens/cssesc#21]
It seems that cssesc does not cater for javascript libraries such as jquery/sizzle that need double escaping.

In the [cssesc notes](https://mathiasbynens.be/notes/css-escapes#css) it mentions the slightly different requirements of libraries like jquery/sizzle and that they need double back-slashing:

`libraries that rely on the same syntax (e.g. jQuery/Sizzle), you would have to take the escaped CSS selectors and escape them again. All you really have to do is double every backslash in the CSS selector `

This is exactly what I need, but after testing, I don't see that cssesc has any facility for this. I am kind of expecting an option in the API like `doubleEscape` or something - otherwise I'm confused as to why this issue is mentioned in the notes but not catered for?

My use-case is a string in existing code that is assumed to be ok for use as an ID in a jquery selector - but in some cases is not `$('not.really[ok]')` so I was using cssesc to blanket that variable eg `$(cssesc('not.really[ok]', { useIdentifier: true } ))`

But this doesn't work because it doesn't create the double-slash required and it looks like I need something else altogether.

Am I missing anything?

**Comment by mathiasbynens** [comment]
- cssesc implements CSS escaping rules.
- [jsesc](https://github.com/mathiasbynens/jsesc) implements JS escaping rules.

In this case it sounds like you want `jsesc(cssesc(input))`.

**Comment by Izhaki** [comment]
I can see the SOC police being very happy with the proposed resolution, but do we really need to add 3.2kB (jsesc) just for that?

After all, our intent is to be able to give `querySelector` a valid selector - does this really belong to JS more than to CSS?

Would it be that hard to add an option for double-slashes?

---

For others seeing this issue, this worked for me ([source](https://stackoverflow.com/a/19702783/1179377)):

```js
const escapeSelector = selector =>
  selector
    .replace(/\\/g, '\\\\')
    .replace(/([ #;&,.+*~\':"@!^$[\]()<=>|\/\{\}\?])/g, '\\$1');
```

**Comment by mathiasbynens** [comment]
@Izhaki Why not just use `CSS.escape` or `cssesc` as I mentioned? I’m still not sure what jsesc has to do with this.

**Comment by Izhaki** [comment]
Doesn't work. I have an element with id `lfo/out` and from `CSS.escape` or `cssesc` (`'isIdentifier': true`) I get an error. In other words, this code:

```js
rootElement.querySelector(`#${CSS.escape(id)}`) // id = 'lfo/out'
```

Yields an error (whereas `#lfo\\/out` works).

**Comment by mathiasbynens** [comment]
It doesn’t work because you’re confusing the different layers of escaping.

At the risk of sounding like a broken record, `cssesc` & `CSS.escape` turn a given input into a valid CSS identifier.

Based on https://github.com/mathiasbynens/cssesc/issues/21#issuecomment-552252581, you then want to take that CSS identifier and use it in a JavaScript string literal. JS string literals have escaping rules of their own, which `jsesc` [or even `JSON.stringify`](https://v8.dev/features/subsume-json) can help with.

Did you see <https://mothereff.in/css-escapes#0lfo%2Fout>? For your particular example, you could just use `document.getElementById` which avoids the need to CSS-escape.

**Comment by mathiasbynens** [comment]
I’ve answered the StackOverflow thread you pointed to: https://stackoverflow.com/a/58794413/96656
