### ISSUE TITLE
Semi-colons are not escaped

### ISSUE THREAD

**Issue by cnorthwood** [mathiasbynens/cssesc#26]
When passing a semi-colon in, I would expect it to be escaped, but they are not.

**Comment by mathiasbynens** [comment]
This should be easy to fix, by adding an entry to https://github.com/mathiasbynens/cssesc/blob/cb894eb42f27c8d3cd793f16afe35b3ab38000a1/src/data.js#L4-L9. @cnorthwood Do you wanna give this a try?

**Comment by cnorthwood** [comment]
So the bit I'm confused by is that it's already in that list, and I haven't dug into the code too much to figure out why it (and braces) aren't getting replaced

**Comment by mathiasbynens** [comment]
From reading the source code it should hit this branch: https://github.com/mathiasbynens/cssesc/blob/cb894eb42f27c8d3cd793f16afe35b3ab38000a1/src/cssesc.js#L75 and escape the semicolon. Can you provide a quick repro script that demonstrates the issue? I'm wondering if you're using some unexpected combination of special options.

**Comment by cnorthwood** [comment]
Ah, so that'd only trigger if the passed in string was an identifier, so I can see that's the case:

```
$ node_modules/.bin/cssesc 'sans-serif; }; body { background-color: blue }; * {'
sans-serif; }; body { background-color: blue }; * {
$ node_modules/.bin/cssesc -i 'sans-serif; }; body { background-color: blue }; * {'
sans-serif\;\ \}\;\ body\ \{\ background-color\:\ blue\ \}\;\ \*\ \{
```

The use case I have is that we allow users to set a custom font which is included in a generated stylesheet, so we do something a bit like this in our code:

```css
:root {
  --font-family: {{ cssesc(site.customFontFamily) }};
}
```

and I was hoping that cssesc would be a solution to avoid any injection security issues (using `CSS.escape` in the browser does correctly escape them). Have I misunderstood the intended use of the API here?

(simply using identifier escaping doesn't work for us either, as one of the other tweakable parameters are colours, and # gets escaped as it thinks it's an ID)

**Comment by mathiasbynens** [comment]
This is definitely a situation where you want to use [the `isIdentifier` option](https://github.com/mathiasbynens/cssesc#isidentifier). The other option would be to [quote](https://github.com/mathiasbynens/cssesc#quotes) it and insert it as a string.

**Comment by cnorthwood** [comment]
hmm, I'd have expected `isIdentifier` only to be used with identifiers rather than values

**Comment by mathiasbynens** [comment]
You're defining a `font-family` name (through a CSS custom property) without wrapping its value in quotes. That's an identifier (or a space-separated set of identifiers), both of which cssesc can handle through the `isIdentifier` option. https://mathiasbynens.be/notes/unquoted-font-family

**Comment by cnorthwood** [comment]
So quoting or using `isIdentifier` doesn't quite work for me as for the font options can be specified by our end users as a full set of font-family font names, and the commas now get escaped. Additionally, for the CSS vars which are colours, using `isIdentifier` behaves as follows:

```
$ node_modules/.bin/cssesc -i 'rgba(255, 255, 255, 0.8)'
rgba\(255\,\ 255\,\ 255\,\ 0\.8\)
``` 

which isn't right either

I'm not sure why cssesc wouldn't be expected to escape `{ } ;` and other syntactically important characters without isIdentifier being specified? I suspect this library isn't that useful for my use case (escaping CSS variable values when including them in server-side rendered template) which is okay as I can try and find another one if it's not a use case you're wanting to support.

**Comment by mathiasbynens** [comment]
> I'm not sure why cssesc wouldn't be expected to escape `{ } ;` and other syntactically important characters without isIdentifier being specified? I suspect this library isn't that useful for my use case (escaping CSS variable values when including them in server-side rendered template) which is okay as I can try and find another one if it's not a use case you're wanting to support.

cssesc can produce two kinds of output: output for use in CSS string literals, or output for use as an identifier. By default it produces the former, which is why `{ } ;` etc. aren't escaped. The `isIdentifier` option lets you do the latter.

> So quoting or using `isIdentifier` doesn't quite work for me as for the font options can be specified by our end users as a full set of font-family font names, and the commas now get escaped.

For this specific use case, you need more than just `cssesc`. You'd want to (conceptually) split the user-defined value on `,` and then CSS-escape each part, unless it's wrapped in quotes. To do this correctly you need a CSS parser. (You can't literally `.split(',')` since that would catch commas in font-family names.)

The same goes for the other use case `rgba`.

cssesc _only_ handles producing either an identifier or a string literal for you. It sounds like you need some additional logic that first parses the user input to determine which parts need escaping first --- cssesc cannot do this for you.

**Comment by cnorthwood** [comment]
no worries, sorry to waste your time - was driven here by the note on https://github.com/mathiasbynens/CSS.escape that this is more powerful but actually it looks like this doesn't do want we want unlike the browser-native CSS.escape. Assuming the polyfill matches the browser behaviour then that'll do what we want.

**Comment by mathiasbynens** [comment]
@cnorthwood No worries, it's not a waste of time at all :)

> Assuming the polyfill matches the browser behaviour then that'll do what we want.

The polyfill does match the native `CSS.escape`, but I don't see how that helps you, since `CSS.escape` solves the same problem as `cssesc` (except cssesc gives you more control over the output). E.g. `CSS.escape(',')` escapes the comma (which it's supposed to do!) as well.

**Comment by cnorthwood** [comment]
Yeah, I've discovered that on further investigation. What I've actually ended up with is `cssesc(value).replace(/;/g, "\\;").replace(/}/g, "\\}").replace(/{/g, "\\{");` which I think is producing valid, safe CSS values.
