### ISSUE TITLE
NPM installation of cssesc fails with TAR_BAD_ARCHIVE error

### ISSUE THREAD

**Issue by vishalvx** [mathiasbynens/cssesc#34]
While installing dependencies in my project, the installation of `cssesc` fails due to a `TAR_BAD_ARCHIVE` error. This package is not a direct dependency but an internal dependency.  

---

### **Environment Details**  
- **Node.js Version**: `18.20.5`  
- **NPM Version**: `10.7.0`  
- **Operating System**: macOS  

---

### **Steps to Reproduce**  
1. Run the following command in the terminal:  
   ```bash
   npm install cssesc
   ```  
   
2. The following error occurs during installation:  
   ```
   npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
   npm ERR! code TAR_BAD_ARCHIVE
   npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format
   ```

---

### **Workarounds Tried**  
- I have also tried this in a separate environment to verify whether it is a project-specific issue.
- Cleared the cache using the following command:  
   ```bash
   npm cache clean --force
   ```
   
 Any help or guidance on resolving this issue would be greatly appreciated.

**Comment by rajeshstarlite** [comment]
Thank you for posting [vishalvx](https://github.com/vishalvx)

I'm also facing the same. Here is complete log

750 http fetch GET 304 https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz 373ms (cache skip)
751 warn tar TAR_BAD_ARCHIVE: Unrecognized archive format
752 silly tar Error: TAR_BAD_ARCHIVE: Unrecognized archive format
752 silly tar at Unpack.warn (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/warn-mixin.js:21:40)
752 silly tar at Unpack.warn (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/unpack.js:236:18)
752 silly tar at Unpack. (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:83:14)
752 silly tar at Unpack.emit (node:events:530:35)
752 silly tar at [emit] (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:313:12)
752 silly tar at [maybeEnd] (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:468:17)
752 silly tar at [consumeChunk] (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:476:21)
752 silly tar at Unpack.write (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:427:25)
752 silly tar at Unpack.end (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:548:14)
752 silly tar at Pipe.end (/usr/local/Cellar/nvm/0.40.0/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/pacote/node_modules/minipass/index.js:84:34) {
752 silly tar recoverable: false,
752 silly tar cwd: '/usr/local/var/www/my-vue-installer/vue-project/node_modules/postcss-selector-parser/node_modules/cssesc',
752 silly tar code: 'TAR_BAD_ARCHIVE',
752 silly tar tarCode: 'TAR_BAD_ARCHIVE'
752 silly tar }

After more research, it appears that https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz doesn't exist on the registry.npmjs.org

**Comment by rajeshstarlite** [comment]
we can watch more https://github.com/tailwindlabs/tailwindcss/issues/15419#issuecomment-2548433766

 https://status.npmjs.org/incidents/bxvmmvlqzfds

**Comment by rajeshstarlite** [comment]
[vishalvx](https://github.com/vishalvx) now it works for me. You can try

**Comment by vishalvx** [comment]
Yep, it’s working now. Thanks, @rajeshstarlite!
I also came across the related npm issue thread [here](https://github.com/npm/cli/issues/7893)
[https://status.npmjs.org/](https://status.npmjs.org/)
![image (1)](https://github.com/user-attachments/assets/ee8c2f56-6fb0-4af0-a80f-81cd53dc80f4)

Closing this issue now.
