### ISSUE TITLE
Create a SASS function for escaping CSS?

### ISSUE THREAD

**Issue by sevenupcan** [mathiasbynens/cssesc#5]
I've tried having a stab at converting cssesc to a function to use within SASS, but I neither have a background in programming or ruby on rails so I didn't get very far.

Such a function would prove very useful in SASS because if certain strings are not escaped they get misinterpreted by SASS.

For example if you want to write:

```
.col-2>md {

}
```

SASS will compile it to:
```
.col-2 > md {

}
```

A function like:

```
$string: cssesc(">md");
.col-2#{string} {

}
```

Would help solve this issue.

**Comment by borodean** [comment]
@sevenupcan here you go: https://github.com/borodean/sassy-escape

**Comment by mathiasbynens** [comment]
Awesome work, @borodean!

**Comment by sevenupcan** [comment]
Yes, thank you very much for this @borodean . :+1:
